apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.release.namespace }}
  labels:
    app: {{ .Values.service.name }}
    role: "frontend"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.service.name }}
